Create snapshots with normalized sizes
swapdisk/lvm_snapshots pull request #11
Opened 2023-08-09 13:55 UTC by ygalblum

check.py - print new volumes array with normalized values when successful
role - use the normalized array instead of the one passed by the user
Test Infra - Allow creating multiple volumes and snapshots 
Tests: Add test to verify that FREE based snapshots with the same percentage get the same size

2023-08-10 18:45 UTC, swapdisk requested changes
The create action is not working for me. For example, I'm running with this...
```yaml
  lvm_snapshots_volumes:
    - vg: rhel_rhel7
      lv: root
      size: 1g
    - vg: rhel_rhel7
      lv: data
      size: 1g
```
My VG has 10g free, so plenty of free space for this. I'm seeing the same issue using percent of or absolute sizes.

When I run the create action, I see the space check passes... 
```
TASK [lvm_snapshots : Verify that there is enough storage space] ***************
task path: /home/bmader/swapdisk/ygalblum/ipu-lvm-snapshot/roles/lvm_snapshots/tasks/check.yml:9
ok: [default] => changed=false 
  failed_when_result: false
  rc: 0
  stderr: |-
    Shared connection to 192.168.122.63 closed.
  stderr_lines: <omitted>
  stdout: |-
    [{"lv": "root", "size": 1073741824.0, "vg": "rhel_rhel7"}, {"lv": "data", "size": 1073741824.0, "vg": "rhel_rhel7"}]
  stdout_lines: <omitted>
Thursday 10 August 2023  13:31:51 -0500 (0:00:00.203)       0:00:02.663 ******* 

TASK [lvm_snapshots : Store check return in case of failure] *******************
task path: /home/bmader/swapdisk/ygalblum/ipu-lvm-snapshot/roles/lvm_snapshots/tasks/check.yml:21
skipping: [default] => changed=false 
  skip_reason: Conditional result was False
Thursday 10 August 2023  13:31:51 -0500 (0:00:00.020)       0:00:02.709 ******* 

TASK [lvm_snapshots : Assert results] ******************************************
task path: /home/bmader/swapdisk/ygalblum/ipu-lvm-snapshot/roles/lvm_snapshots/tasks/check.yml:26
ok: [default] => changed=false 
  msg: The Volume Groups have enough space to create the requested snapshots
Thursday 10 August 2023  13:31:51 -0500 (0:00:00.024)       0:00:02.734 ******* 
```
But when it tries to create the snapshots, the task fails with insufficient space...
```
TASK [lvm_snapshots : Create snapshots] ****************************************
task path: /home/bmader/swapdisk/ygalblum/ipu-lvm-snapshot/roles/lvm_snapshots/tasks/create.yml:30
failed: [default] (item={'lv': 'root', 'size': 1073741824.0, 'vg': 'rhel_rhel7'}) => changed=false 
  ansible_loop_var: item
  err: |2-
      Volume group "rhel_rhel7" has insufficient free space (2559 extents): 32124 required.
  invocation:
    module_args:
      active: true
      force: false
      lv: root
      opts: null
      pvs: null
      resizefs: false
      shrink: true
      size: '1073741824.0'
      snapshot: root_ripu
      state: present
      thinpool: null
      vg: rhel_rhel7
  item:
    lv: root
    size: 1073741824.0
    vg: rhel_rhel7
  msg: Creating logical volume 'root' failed
  rc: 5
```
Looks like maybe we are passing bytes to lvol, but it's defaulting to megabytes?

2023-08-13 08:23 UTC, ygalblum commented
First, you are right, the issue was that the default unit is megabytes. The returned JSON should include the unit type 'B'.

But, I needed to understand why my tests did not fail. The reason it failed was that the test was requesting the snapshot size smaller than the size of the original volume. As a result, `lvcreate` limited the request to the size of the volume. Since there are two volumes each of 2G and therefore two snapshots (again each of 2G) totaling the request to 8G on a 9G volume, the test passed. Once I've changed the volumes' sizes to 3G, the test started failing as expected.

However, even with the fix, using `50%FREE` still passed the check and failed the creation So, I investigated further and found that the size of a logical volume must align to the size of the extent of the volume group and the lvcreate command rounds up the request automatically. As a result, a request for 2 snapshots each of 50%FREE passed the check, but failed the creation because the first request took more than 50% of the free due to alignment. 

The fix to the second issue should have probably gone to a separate PR. But, at the current stage of the repo, I guess we can live with adding it as part of this one.

2023-08-14 15:01 UTC, swapdisk commented
No problem. I'll play with this in my lab environment today.

2023-08-14 18:47 UTC, swapdisk commented
Everything works in my RHEL7 lab. LGTM.

2023-08-14 18:47 UTC, merged