Revert - wait for all snapshots to drain before returning
swapdisk/lvm_snapshots pull request #15
Opened 2023-09-28 08:50 UTC by ygalblum

Add a check that the all snapshots were drained
Add test
Add changelog fragement

2023-09-28 15:24 UTC, swapdisk requested changes
I made one suggestion. Otherwise, LGTM.

2023-09-28 15:24 UTC, swapdisk commented on roles/lvm_snapshots/tasks/revert.yml
> +  ansible.builtin.command: "lvs --select 'lv_name = {{ item.origin }}' --reportformat json"
To guarantee  we are looking at the expected LV?... 
```suggestion
  ansible.builtin.command: "lvs --select 'vg_name = {{ item.vg_name }} && lv_name = {{ item.origin }}' --reportformat json"
```

2023-10-01 06:38 UTC, ygalblum commented
> I made one suggestion. Otherwise, LGTM.

I've added your fix (thanks for that).

2023-10-02 19:38 UTC, swapdisk approved these changes

2023-10-02 19:39 UTC, merged